'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WbfSsoStockCard
    
    '''<summary>
    '''ScmChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScmChangePassword As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanWork As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DstListWarehouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListWarehouse As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgListWarehouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListWarehouse As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DstListBuilding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListBuilding As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgListBuilding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListBuilding As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ChkStorageOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkStorageOID As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BtnFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblMsgReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgReturn As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DstListLantai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListLantai As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgListLantai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListLantai As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DstListZona control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListZona As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgListZona control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListZona As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblStorageOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblStorageOID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtStorageOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtStorageOID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DstListStorageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListStorageType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgListStorageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListStorageType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanListRackN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanListRackN As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TxtListRackN_Start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListRackN_Start As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgListRackN_Start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListRackN_Start As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanListRackY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanListRackY As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TxtListRackY_SeqNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListRackY_SeqNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListRackY_Column control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListRackY_Column As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListRackY_Level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListRackY_Level As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgListRackY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListRackY As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanListStagging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanListStagging As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''RdbListStagging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbListStagging As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ChkSummByWarehouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSummByWarehouse As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BtnXLS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnXLS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblProgressXLS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblProgressXLS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DstListCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListCompany As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgListCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListCompany As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtListBrgCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListBrgCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListBrgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListBrgName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnListBrgCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListBrgCode As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblMsgListBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListBrg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtListRcvNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListRcvNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnListRcvNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListRcvNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ChkSummAllRcv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSummAllRcv As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LblMsgListRcvNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListRcvNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblMsgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DivLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivLsBrg As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanLsBrg As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLsBrg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnLsBrgClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLsBrgClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLsBrg As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLsBrg As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GrvLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvLsBrg As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DivLsRcvPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivLsRcvPO As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanLsRcvPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanLsRcvPO As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnLsRcvPOClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLsRcvPOClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtLsRcvPONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLsRcvPONo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnLsRcvPOFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLsRcvPOFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GrvLsRcvPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvLsRcvPO As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PanList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GrvList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvList As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''HdfListRcvPOHOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfListRcvPOHOID As Global.System.Web.UI.WebControls.HiddenField
End Class
