'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WbfDmDOTSummary
    
    '''<summary>
    '''ScmChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScmChangePassword As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanWork As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PanButtonH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanButtonH As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DivList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DstCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstCompany As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''BtnNotaFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNotaFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblMsgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanCust As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GrvCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvCust As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DivSM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSM As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanSM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanSM As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblSM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RdlSM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdlSM As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''PanSM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanSM1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GrvSM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvSM1 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''LblSM2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSM2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanSM2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanSM2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GrvSM2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvSM2 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''HdfCompCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfCompCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfCustCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfCustCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfBrgCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfBrgCode As Global.System.Web.UI.WebControls.HiddenField
End Class
