'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WbfSsoSmTRB
    
    '''<summary>
    '''ScmChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScmChangePassword As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanWork As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PanButtonH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanButtonH As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''BtnSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSimpan As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnBaru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBaru As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBatal As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblProgressSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblProgressSave As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnCancelSm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelSm As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnSudahTRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSudahTRB As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPreview As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''BtnListFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblProgressFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblProgressFind As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtListTransID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListTransID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListSalesOrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListSalesOrderNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListStart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListEnd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnListClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DstListWhsFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListWhsFrom As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DstListWhsTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListWhsTo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ChkSt_Baru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSt_Baru As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ChkSt_Closed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSt_Closed As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ChkSt_Cancelled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSt_Cancelled As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''GrvList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvList As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DivConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivConfirm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanConfirm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblConfirmMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblConfirmProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmProgress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbConfirmNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbConfirmNote As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''LblConfirmNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtConfirmNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtConfirmNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblConfirmWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmWarning As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnConfirmYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfirmYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnConfirmNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfirmNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivListSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivListSO As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanListSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanListSO As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblListSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblListSO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnListSOClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListSOClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtListSONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListSONo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListSOCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListSOCust As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSOStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSOStart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSOEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSOEnd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnListSOFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListSOFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnListSOSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListSOSelect As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblMsgListPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgListPO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GrvListSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvListSO As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DivPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivPreview As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanPreview As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ifrPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifrPreview As Global.System.Web.UI.HtmlControls.HtmlIframe
    
    '''<summary>
    '''BtnPreviewClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPreviewClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtSmDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSmDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgSmDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgSmDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DstCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstCompany As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgCompany As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtTransID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSmNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSmNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DstSubWhsFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstSubWhsFrom As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgSubWhsFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgSubWhsFrom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtTransStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DstSubWhsTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstSubWhsTo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgSubWhsTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgSubWhsTo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RdbDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbDS As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ChkSummNonZero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSummNonZero As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BtnRefreshSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefreshSum As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblRefreshSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblRefreshSum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblMsgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GrvSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvSum As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''GrvDetail_SO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvDetail_SO As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''HdfTransStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfTransStatus As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfProcess As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfRowIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfRowIdx As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfActionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfActionStatus As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfDetailRowIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfDetailRowIdx As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfDetailOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfDetailOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfStatusBaru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfStatusBaru As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfStatusPrepare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfStatusPrepare As Global.System.Web.UI.WebControls.HiddenField
End Class
