'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WbfSsoDispatchDMDs
    
    '''<summary>
    '''ScmChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScmChangePassword As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanWork As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PanButtonH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanButtonH As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''BtnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSimpan As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBatal As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblProgressSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblProgressSave As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnCancelDSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelDSP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblXlsProses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblXlsProses As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblMsgXlsProsesError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgXlsProsesError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DivList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''BtnListFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblProgressFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblProgressFind As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtListTransID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListTransID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListStart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListEnd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnListClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DstListWhs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListWhs As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ChkSt_OnDispatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSt_OnDispatch As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ChkSt_DispatchDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSt_DispatchDone As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ChkSt_DriverConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSt_DriverConfirm As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ChkSt_Closed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSt_Closed As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ChkSt_Cancelled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkSt_Cancelled As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''GrvList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvList As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DivConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivConfirm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanConfirm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblConfirmMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblConfirmProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmProgress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbConfirmNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbConfirmNote As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''LblConfirmNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtConfirmNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtConfirmNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblConfirmWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmWarning As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnConfirmYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfirmYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnConfirmNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfirmNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivPrOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivPrOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanPrOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanPrOption As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DstProReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstProReport As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ChkProVarianOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkProVarianOnly As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RdbProXls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbProXls As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''BtnProOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnProOK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnProCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnProCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivSKK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSKK As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanSKK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanSKK As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblSKKprogress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSKKprogress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnSKKFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSKKFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtSKKFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSKKFind As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnSKKClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSKKClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblSKKError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSKKError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GrvSKK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvSKK As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DivPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivPreview As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanPreview As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ifrPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifrPreview As Global.System.Web.UI.HtmlControls.HtmlIframe
    
    '''<summary>
    '''BtnPreviewClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPreviewClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tbTrans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTrans As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''TxtTransNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCompany As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTransID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTransDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtWhs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtWhs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTransStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtSKKOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSKKOID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSKKNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSKKNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnSKK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSKK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtTransDriver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransDriver As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTransVehicle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransVehicle As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanLsPick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanLsPick As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GrvLsPick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvLsPick As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PanData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanData As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblDataTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDataTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanData_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanData_D As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GrvData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvData As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''HdfDataRowIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfDataRowIdx As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfProcess As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfTransStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfTransStatus As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfRowIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfRowIdx As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfDetailRowIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfDetailRowIdx As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfPCKHOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfPCKHOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfCompanyCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfCompanyCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfProcessDataKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfProcessDataKey As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfDriverOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfDriverOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfVehicleOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfVehicleOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfDcmSchHOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfDcmSchHOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfDcmSchDriverOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfDcmSchDriverOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfDcmVehicleOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfDcmVehicleOID As Global.System.Web.UI.WebControls.HiddenField
End Class
