'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WbfUserGroupMs
    
    '''<summary>
    '''ScmChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScmChangePassword As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanWork As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TxtOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtOID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ChkActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkActive As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TxtUGName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUGName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgUGName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgUGName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtUGDescr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUGDescr As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgUGDescr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgUGDescr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblMsgErrorNE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgErrorNE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''HdfActionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfActionStatus As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''BtnSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSimpan As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnBaru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBaru As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBatal As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblMsgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtKriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtKriteria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GrvList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvList As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PanAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanAccess As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GrvAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvAccess As Global.System.Web.UI.WebControls.GridView
End Class
