'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WbfSsoSalesOrderCancel
    
    '''<summary>
    '''ScmChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScmChangePassword As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanWork As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PanButtonH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanButtonH As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''BtnSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSimpan As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnBaru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBaru As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBatal As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblProgressSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblProgressSave As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnCancelVoidSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelVoidSO As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnPrepare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPrepare As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPreview As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''BtnListFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblProgressFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblProgressFind As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtListTransID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListTransID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListSalesOrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListSalesOrderNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListStart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListEnd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnListClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnListClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GrvList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvList As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DivConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivConfirm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanConfirm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblConfirmMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblConfirmProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmProgress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbConfirmNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbConfirmNote As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''LblConfirmNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtConfirmNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtConfirmNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblConfirmWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmWarning As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblConfirmError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnConfirmYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfirmYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnConfirmNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfirmNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivLsSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivLsSO As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanLsSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanLsSO As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblLsSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLsSO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnLsSOClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLsSOClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtLsSONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLsSONo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgLsSONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgLsSONo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLsSOCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLsSOCustomer As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnLsSOFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLsSOFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtLsSOStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLsSOStart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtLsSOEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLsSOEnd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''GrvLsSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvLsSO As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DivPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivPreview As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanPreview As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ifrPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifrPreview As Global.System.Web.UI.HtmlControls.HtmlIframe
    
    '''<summary>
    '''BtnPreviewClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPreviewClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DstCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstCompany As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgCompany As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtSOOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSOOID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTransID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSONo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnSONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSONo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblMsgSONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgSONo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtSOVoidDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSOVoidDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgSOVoidDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgSOVoidDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtTransStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtSODate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSODate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSOVoidNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSOVoidNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSOVoidNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSOVoidNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgSOVoidNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgSOVoidNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtSOCustCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSOCustCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSOCustName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSOCustName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSOCustAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSOCustAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSOCustCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSOCustCity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtInvPRIOCancelNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtInvPRIOCancelNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GrvDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvDetail As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''HdfTransStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfTransStatus As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfProcess As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfRowIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfRowIdx As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfActionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfActionStatus As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfDetailRowIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfDetailRowIdx As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfDetailOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfDetailOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfStatusBaru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfStatusBaru As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfStatusPrepare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfStatusPrepare As Global.System.Web.UI.WebControls.HiddenField
End Class
