'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WbfSsoSNRequestPrint
    
    '''<summary>
    '''ScmChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScmChangePassword As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanWork As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DstCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstCompany As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgCompany As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DstWarehouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstWarehouse As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgWarehouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgWarehouse As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtOID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtBrgCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBrgCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnBrgCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBrgCode As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtBrgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBrgName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgBrgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgBrgName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtBrgUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBrgUnit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtPrintSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrintSN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgPrintSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgPrintSN As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtPrintNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrintNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMsgPrintNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgPrintNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblGenProses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblGenProses As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblMsgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''HdfOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''BtnPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPrint As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivLsBrg As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanLsBrg As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLsBrg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnLsBrgClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLsBrgClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TxtLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLsBrg As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLsBrg As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GrvLsBrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvLsBrg As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DivPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivPreview As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PanPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanPreview As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ifrPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifrPreview As Global.System.Web.UI.HtmlControls.HtmlIframe
    
    '''<summary>
    '''BtnPreviewClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPreviewClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PanList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DstListCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListCompany As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ChkPrinted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkPrinted As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TxtListBarang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListBarang As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtListSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtListSN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GrvList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvList As Global.System.Web.UI.WebControls.GridView
End Class
