'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WbfSsoCustomerMs
    
    '''<summary>
    '''ScmChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScmChangePassword As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpnList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanWork As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DstCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstCompany As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblMsgCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgCompany As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FupXls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FupXls As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''LblMsgFupXls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgFupXls As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblFupXls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFupXls As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtXlsWorksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtXlsWorksheet As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblXlsWorksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblXlsWorksheet As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblXlsProses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblXlsProses As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblMsgXlsProsesError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgXlsProsesError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblMsgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsgError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnXlsUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnXlsUpload As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PanList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanList As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DstListCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DstListCompany As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TxtKriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtKriteria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GrvList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvList As Global.System.Web.UI.WebControls.GridView
End Class
